<?php
/**
 * Autogenerated from tmTranslator-Module
 */

$sLangName  = '%LANGUAGE_NAME%';

// -------------------------------
// RESOURCE IDENTIFIER = STRING
// -------------------------------
$aLang = array(
    // Standard charset
    'charset' => 'UTF-8'
);
